name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      # Enable Nx Cloud task distribution
      - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Set up Node.js and cache pnpm dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      # Install dependencies using pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Set SHA for Nx tasks
      - uses: nrwl/nx-set-shas@v4

      # Run Nx affected tasks (lint, test, build, e2e)
      - name: Run Nx affected tasks
        run: pnpm exec nx-cloud start-ci-run
        run: pnpm exec nx affected --target=build --parallel --max-parallel=3
        run: pnpm exec nx affected --target=lint --parallel --max-parallel=2
        run: pnpm exec nx affected --target=test --parallel --max-parallel=2